# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-20 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messsge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='\u59d3\u540d')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('address', models.CharField(max_length=50, verbose_name='\u5730\u5740')),
                ('text', models.CharField(max_length=100, verbose_name='\u7559\u8a00')),
                ('creat_time', models.DateTimeField(auto_now=True, verbose_name='\u7559\u8a00\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7559\u8a00',
                'verbose_name_plural': '\u7559\u8a00\u96c6',
            },
        ),
    ]
