# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-21 01:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messsge',
            old_name='text',
            new_name='message',
        ),
    ]
